AWSTemplateFormatVersion: 2010-09-09
Description: ND9991 C3 L4 template
Resources:
  EC2Instance:
    Type: 'AWS::EC2::Instance'
    Properties:
      SecurityGroups:
        - !Ref InstanceSecurityGroup
      KeyName: gray
      ImageId: 'ami-08d4ac5b634553e16'
      InstanceType: t2.micro
      Tags:
        - Key: Project
          Value: "udacity"
  InstanceSecurityGroup:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      GroupDescription: Enable SSH access via port 22
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: '22'
          ToPort: '22'
          CidrIp: 0.0.0.0/0
