---
- name: "install apt packages"
  become: true
  become_method: sudo
  apt:
    update_cache: true
  
- name: "remove dependancies that are no longer required"
  become: true
  apt:
    autoremove: true